### PR TITLE
Fix CPU%

### LINKED ISSUE #3261: Wrong (?) cpu use reported in web interface
### Versions

- Core version is v6.0.3 (Latest: v6.0.4)
- Web version is v6.0.1 (Latest: v6.0.1)
- FTL version is v6.0.2 (Latest: v6.0.2)

### Platform

```
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian


Linux pihole 6.6.31+rpt-rpi-v6 #1 Raspbian 1:6.6.31-1+rpt1 (2024-05-29) armv6l GNU/Linux
```

### Expected behavior

In web UI, there's a "status" area with memory and CPU use displayed.

Since v6, I'm alarmed at CPU figure, and indeed there was an issue (solved after reading another post).

YET : the CPU figure is totally off compared to 'top' or 'htop' figure reported at the same time over ssh.

I would expect the figure to reflect more the reality, it was the case with v5

### Actual behavior / bug

When logging into web UI, CPU  use display is between 40 and 50%.

It may go down / go up for no reason.

At the same time, under an ssh session, reported CPU use is as follow : 

most of the time : 

Image

during a momentary peak : 

Image

### Steps to reproduce

1. Go to admin web UI and log in
2. Look at CPU status on top left corner

## Debug Token

- URL:  

https://tricorder.pi-hole.net/HjxwOLwp/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Two changes:

- Show load instead of CPU % in info box as this (a) is more meaningful (naturally includes IOWait, etc.) and (b) is what we have shown in v5 as well so users are used to seeing these values even if they are less intuitive than CPU % at first
- Still show total CPU % on settings / system info tab for easy contrasting to the CPU % used by FTL

grafik

Needs FTL branch `new/total_cpu` to work https://github.com/pi-hole/FTL/pull/2297

---

**Related issue or feature (if applicable):** Fixes #3261 

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

File: scripts/js/footer.js [hunk 1]
```diff
@@ -360,37 +360,31 @@ function updateSystemInfo() {
...
       $("#cpu").prop(
         "title",
-        "Load: " +
-          system.cpu.load.raw[0].toFixed(2) +
-          " " +
-          system.cpu.load.raw[1].toFixed(2) +
-          " " +
-          system.cpu.load.raw[2].toFixed(2) +
-          " on " +
+        "Shown load metrics are load averages for the past 1, 5, and 15 minutes on a system having " +
```
Comment (rdwebdesign) [inline scripts/js/footer.js]: We can simplify the text here:

```suggestion
        "Load averages for the past 1, 5, and 15 minutes on a system with " +
```
image


Or using a line break:
```suggestion
        "Load averages for the past 1, 5, and 15 minutes\non a system with " +
```
image

**Review by rdwebdesign — CHANGES_REQUESTED** [review]

**Review by rdwebdesign — DISMISSED** [review]

**Comment by DL6ER** [comment]
Still awaiting approval on https://github.com/pi-hole/FTL/pull/2297 - I removed the commit @yubiuser wanted me to revert this morning

**Comment by PromoFaux** [comment]
@DL6ER merge conflicts

**Comment by DL6ER** [comment]
Assuming approval holds over minor merge conflict resolution...

**Review by rdwebdesign — APPROVED** [review]

**Comment by rdwebdesign** [comment]
Re-approved
