### PR TITLE
Hide top tables depending on privacy level

### LINKED ISSUE #3249: Anonymous mode does not hide boxes
### Versions

- Pi-hole:  v6.0.3
- AdminLTE:  v6.0.1
- FTL:  v6.0.2

### Platform

- OS and version:  

- Platform:  Raspberry Pi

### Expected behavior

Top Permitted Domains, Top Blocked Domains, Top Clients (total), Top Clients (blocked only) not beeing hidden when Privacy Settings are in Anonymous mode

### Actual behavior / bug

Boxes should be hidden, not empti

### Steps to reproduce

1. Go to Privacy Settings
2. Click on Anonymous mode:
3. See error

### Screenshots

Image

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Removes the 'top' tables from the dashboard when no data is available due to higher privacy level. This restores v5 behavior. Currently the table is shown with a 'no data' note. 

If the privacy level is not high enough to hide the table but no data is provided (new installations, failures) the tables are shown with a 'no data' info.

Fixes https://github.com/pi-hole/web/issues/3249

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by mwoolweaver** [comment]
My request might actually come true finally. 

https://github.com/pi-hole/web/issues/3068

**Comment by mwoolweaver** [comment]
I tried this previously #3072 and was denied

**Comment by yubiuser** [comment]
Oh... I did not remember this discussion, so many things happend in-between. Maybe the group's opinion changed, let's see.

**Comment by PromoFaux** [comment]
I'm in two minds.

On the one hand I like the "No Data" label - i'm reminded of books with "This page has been intentionally left blank". It is clear that there is explicitly no data to display to the user.

However I can also see that if you're never expecting to see data there then it can be seen as a distraction/superflous table. 

Dare I suggest an additional toggle/setting (default to current behaviour) that allows users that really _don't want_ to see empty tables to hide them?

**Comment by rdwebdesign** [comment]
I understand both points of view. Hiding the tables seems cleaner, but on the other hand, showing "No data" is more precise when there is no data to show.

My only concern here is: This PR is hiding the tables in the absence of data.

What happens if the privacy level is set to zero (show everything), but for some reason (a database issue, misconfiguration or something similar) there is no data? I wouldn't expect to hide the tables in cases like these.

I think we should only hide the tables if privacy level requires to hide them. Otherwise we should show "no data".

**Comment by mwoolweaver** [comment]
i remember on v5 these boxes would show an API error
Screenshot From 2025-04-02 13-05-26

but I'm not sure how that works now that web server is a part of FTL with v6. 

-----

edit:

is it possible for the API to be in a broken state and the WebUI still work?

**Comment by yubiuser** [comment]
> is it possible for the API to be in a broken state and the WebUI still work?

Yes, I think this can happen. E.g. the web server is running but the query database is broken.

File: scripts/js/index.js [hunk 1]
```diff
@@ -292,10 +294,10 @@ function updateTopClientsTable(blocked) {
     let url, percentage;
     const sum = blocked ? data.blocked_queries : data.total_queries;
 
-    // Add note if there are no results (e.g. privacy mode enabled)
+    // Remove table if there are no results (e.g. new
```
Comment (PromoFaux) [inline scripts/js/index.js]: > e.g new installation...

This is an important distinction here.

Can we not just check the API to see what privacy mode we're on and display/hide accordingly?

Comment (yubiuser) [reply scripts/js/index.js]: Good point. I addressed this in the second commit.

**Comment by dschaper** [comment]
I'd separate the two situations.

1. If the data is missing because of Privacy levels then hide the boxen. 

-or-

2. If the data is expected but missing then leave the boxes and indicate either `no data` or the reason why there is no data if that reason is known.

The idea of a toggle is nice but where is the state for that toggle stored? Should it be for every browser or browser/user/session specific.

**Comment by rdwebdesign** [comment]
I agree. We should hide the tables only if it is required by privacy level, otherwise show "No data".

> The idea of a toggle is nice but where is the state for that toggle stored? Should it be for every browser or browser/user/session specific.

I'm not sure if a toggle is necessary. We already can check the Privacy level using the API and hide/show the tables.

**Comment by dschaper** [comment]
Toggle would be for "I know what I set the Privacy level at but I want to see|not see it!"

**Comment by rdwebdesign** [comment]
Hmmm... I see. An override toggle.

Personally I think this is too much.

**Comment by yubiuser** [comment]
> I'd separate the two situations.
>
>If the data is missing because of Privacy levels then hide the boxen.
>-or-
>
>If the data is expected but missing then leave the boxes and indicate either no data or the reason why there is no data if that reason is known.

This is what the PR does. E.g. for one box

https://github.com/pi-hole/web/blob/f48ff7191b83980d9552f7e0997d8a98f139a528/scripts/js/index.js#L323-L335


If Privacy levels is high enough, boxes are always hidden. If they are shown, but no data is there, we add a hint to the box.

___

I don't think we need a toggle for "I know what I set the Privacy level at but I want to see|not see it!"
This PR already deals with an edge-case, but making this configurable is too much in my opinion. If someone want to implement this, this could be done in a follow up PR

**Review by rdwebdesign — APPROVED** [review]
I agree with the current options used in this PR:
- tables should be hidden according to privacy level and
- we don't need a toggle to override the behavior

From my point of view this PR is approved as it is, but since we had multiple opinions about how this should be done, I'm asking for another approval from a team member before merging.

**Review by PromoFaux — APPROVED** [review]

**Comment by XhmikosR** [comment]
@yubiuser note that footer.js already calls the same API endpoint.

It's not a good practice to make duplicate requests, but I guess we can refactor it later after I land my changes.

**Comment by yubiuser** [comment]
I know, but there was a race condition. Depending on which js loaded faster the hiding worked or did not.

**Comment by XhmikosR** [comment]
Can you please try my branch? https://github.com/XhmikosR/web/tree/xmr/reduce-jquery3

I moved the code to footer, maybe it works fine there.

**Comment by yubiuser** [comment]
> I moved the code to footer, maybe it works fine there.

It does not.

**Comment by XhmikosR** [comment]
We really need to figure out the scripts order eventually because it keeps biting us in the ass...

Unfortunately, my attempt at it in #3302 didn't work.
