### PR TITLE
Don't try to fill client/domain tables if there is no data

### LINKED ISSUE #3068: [development-v6] Top Domains and Top Clients are not hidden when they contain no data
was originally opened as pi-hole/pi-hole/issues/5699 in error

### Versions

Core
    Version is v5.18.2-400-g8b324741 (Latest: null)
    Branch is development-v6
    Hash is 8b324741 (Latest: 8b324741)

Web
    Version is v5.19-818-ge852fbb2 (Latest: null)
    Branch is development-v6
    Hash is  e852fbb2  (Latest: e852fbb2 )

FTL
    Version is vDev-5c97d29 (Latest: null)
    Branch is development-v6
    Hash is 5c97d290  (Latest: 5c97d290 )

### Platform

- OS and version:  Ubuntu 24.04 LTS

- Platform:  Raspberry Pi 4 Model B Rev 1.1

### Expected behavior

when privacy mode is set to anything other than `Show Everything`  the last 4 boxes should be hidden when they contain no data.

### Actual behavior / bug

when privacy mode is set to anything other than `Show Everything`  the last 4 boxes show a loading wheel endlessly when they contain no data.

### Steps to reproduce

1. set privacy mode to anything other than `Show Everything`
2. go to the dashboard 
3. Scroll down to the bottom of the dashboard (http://pi.hole/admin/)
4. See boxes with loading wheels, how many depends on privacy mode selection ( as seen in screenshots )

## Debug Token

- URL:  https://tricorder.pi-hole.net/tog4t1Nu/

#### This is when `Anonymous mode` & `Hide domains and clients` is selected 
Screenshot from 2024-07-07 21-09-56 

#### This is when `Hide domains` is selected 
Screenshot from 2024-07-07 21-45-52

### Additional context

Worth noting is an old issue that's very similar #932 the fix was #966

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Fixes https://github.com/pi-hole/web/issues/3068.

Do not try to populate top domain/client tables at the dashboard if there is no data to fill in.
---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

File: scripts/pi-hole/js/index.js [hunk 1]
```diff
@@ -295,31 +295,30 @@ function updateTopClientsTable(blocked) {
...
-        encodeURIComponent(client.ip) +
-        '">' +
-        utils.escapeHtml(clientname) +
-        "</a>";
-      percentage = (client.count / sum) * 100;
-
-      // Add row to table
-      clienttable.append(
-        "<tr> " +
+    } else {
```
Comment (DL6ER) [inline scripts/pi-hole/js/index.js]: Wouldn't it be easier to simply `return` here instead of making so many changes by moving stuff into a new `else` branch?

File: scripts/pi-hole/js/index.js [hunk 2]
```diff
@@ -352,25 +351,24 @@ function updateTopDomainsTable(blocked) {
...
-    data.domains.forEach(function (item) {
-      // Sanitize domain
-      domain = encodeURIComponent(item.domain);
-      // Substitute "." for empty domain lookups
-      urlText = domain === "" ? "." : domain;
-      url = '<a href="queries.lp?domain=' + domain + '">' + urlText + "</a>";
-      percentage = (item.count / sum) * 100;
-      domaintable.append(
-        "<tr> " +
+    } else {
```
Comment (DL6ER) [inline scripts/pi-hole/js/index.js]: Same as above

**Comment by yubiuser** [comment]
Force pushed the changes.

**Review by rdwebdesign — APPROVED** [review]
