### PR TITLE
Include link to current docker tag if on docker. Closes #2323

### LINKED ISSUE #2323: Docker Tag for link for Release 2022.09 is not clickable anymore
This is a: **Bug***

## Details
Starting with [Release 2022.09](https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.09) the link for "Docker Tag" for Pi-hole is not clickable anymore:
> Docker Tag 2022.09 Pi-hole [v5.12](https://github.com/pi-hole/pi-hole/releases/v5.12) FTL [v5.17](https://github.com/pi-hole/FTL/releases/v5.17) Web Interface [v5.14](https://github.com/pi-hole/AdminLTE/releases/v5.14)

Before:
> Docker Tag [2022.08.2](https://github.com/pi-hole/docker-pi-hole/releases/2022.08.2) Pi-hole [v5.11.4](https://github.com/pi-hole/pi-hole/releases/v5.11.4) FTL [v5.16.3](https://github.com/pi-hole/FTL/releases/v5.16.3) Web Interface [v5.13](https://github.com/pi-hole/AdminLTE/releases/v5.13)
> Docker Tag [2022.08.3](https://github.com/pi-hole/docker-pi-hole/releases/2022.08.3) Pi-hole [v5.11.4](https://github.com/pi-hole/pi-hole/releases/v5.11.4) FTL [v5.16.3](https://github.com/pi-hole/FTL/releases/v5.16.3) Web Interface [v5.13](https://github.com/pi-hole/AdminLTE/releases/v5.13)

## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 
See your Docker Tag down below your web GUI.

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

Slight omission with the re-jigging of the footer stuff. Happens to the best of us!

We can push this out as a hotfix, no need to wait

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

File: scripts/pi-hole/php/footer.php [hunk 1]
```diff
@@ -65,10 +65,10 @@
         <div class="row row-centered text-center version-info">
             <div class="col-xs-12 col-sm-12 col-md-10">
                 <ul class="<?php echo $list_class; ?>">
-                    <?php if ($docker_current) { ?>
+                    <?php if ($dockerVersionStr) { ?>
```
Comment (rdwebdesign) [inline scripts/pi-hole/php/footer.php:68]: I used `$docker_current` here for consistency and because its' value is a _boolean_.

Comment (PromoFaux) [reply scripts/pi-hole/php/footer.php:68]: `$docker_current` is a string... it's currently `2022.09`

**Review by rdwebdesign — APPROVED** [review]
