### PR TITLE
Fix the wrong escaping on settings datatable

### LINKED ISSUE #1513: HTML code escaping into GUI
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behavior:**

`A couple of places in the GUI should display normal text; in one case, the font should be italicized and in the other case it should display a single quote`

**Actual behavior:**

`In Settings -> DHCP under Current Leases, I see "<i>unknown</i>" ... for the other, under Group Management -> Clients, after adjusting an entries group membership and applying, the single quote is replaced by "&#039;" when the next entry still correctly displays the single quote.`

[Screenshots of the two issues in the GUI](https://postimg.cc/gallery/sS4NYb0)

**Steps to reproduce:**

`It started behaving this way as soon as I updated to 5.1`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/8wxv08x886`

**Troubleshooting undertaken, and/or other relevant information:**

`I have not attempted to fix this issue`

### PR DESCRIPTION
**Pull request by rdwebdesign**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Fix #1513 

**How does this PR accomplish the above?:**

The datatable formarter `render: $.fn.dataTable.render.text()` escapes every HTML tag inside the cell, transforming `<i>unknown</i>` into `&lt;i&gt;unknown&lt;/i&gt;`.

**What documentation changes (if any) are needed to support this PR?:**

none

### CODE REVIEW

File: scripts/pi-hole/js/settings.js [hunk 1]
```diff
@@ -268,9 +268,26 @@ $(function () {
...
+          targets: 2,
+          render: function (data) {
+            // Show "unknown", when host is "*"
+            var str;
+            if (data === "*") {
+              str = "<i>unknown</i>";
+            } else {
+              str =
+                typeof data === "string"
+                  ? data.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
```
Comment (DL6ER) [inline scripts/pi-hole/js/settings.js]: Shouldn't we use a library provided escaping function here?

Comment (rdwebdesign) [reply scripts/pi-hole/js/settings.js]: I copied this from the source code, but I just find out I used the old version.

Comment (rdwebdesign) [reply scripts/pi-hole/js/settings.js]: Now using `utils.escapeHtml()`.

**Review by DL6ER — APPROVED** [review]

**Comment by yubiuser** [comment]
This should be extended to currently active leases

https://github.com/pi-hole/AdminLTE/blob/bf82c47e980c5cec5b6d4f8d23d5dcbd1f702077/scripts/pi-hole/js/settings.js#L241

I did not follow the code completely but this looks suspicious as well

https://github.com/pi-hole/AdminLTE/blob/bf82c47e980c5cec5b6d4f8d23d5dcbd1f702077/settings.php#L601

**Comment by rdwebdesign** [comment]
> I did not follow the code completely but this looks suspicious as well

No.

The line 601 includes a `<i>` tag for a different element (to format the tooltip text). 
This element will not be touched by javascript function, so it will not cause problems.
