### PR TITLE
Fix bug with secs/mins buttons on disable menu caused by addition of theming.

### LINKED ISSUE #1587: Disable for custom time in seconds and not in minutes
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behavior:**

Disabling Pihole for a custom time should be done in minutes (like in previous) versions and not in seconds.

**Actual behavior:**

Disabling Pihole for a custom time is done in seconds.

**Steps to reproduce:**

Select `Disable` -> `Custom time` and accept the default value (60)

image

The time is set in seconds but not in minutes:
image

I'm using and this wasn't happening on Pi-hole `5.1.0`

```
Pi-hole v5.1.1 Web Interface v5.1 FTL v5.1
```

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Fixes #1587

**How does this PR accomplish the above?:**

Exclude the mins/secs buttons from being rethemed, as they use button clases rather than iCheck in any case.

See below, checkbox/radios in background still being themed, buttons in foreground not touched.

image

**What documentation changes (if any) are needed to support this PR?:**

none

### CODE REVIEW

File: scripts/pi-hole/js/footer.js [hunk 1]
```diff
@@ -133,7 +133,7 @@ function initCheckboxRadioStyle() {
 
   function applyCheckboxRadioStyle(style) {
     boxsheet.attr("href", getCheckboxURL(style));
-    var sel = $("input[type='radio'],input[type='checkbox']");
+    var sel = $("input[type='radio'],input[type='checkbox']").not("#selSec").not("#selMin");
```
Comment (DL6ER) [inline scripts/pi-hole/js/footer.js:137]: Can you add a comment above this? Otherwise, in a few months, we will have forgotten what `selSec` and `selMin` in and why it is excluded here.

Comment (PromoFaux) [reply scripts/pi-hole/js/footer.js:137]:
```suggestion
    // Get all radio/checkboxes for theming, with the exception of the two radio buttons on the custom disable timer
    var sel = $("input[type='radio'],input[type='checkbox']").not("#selSec").not("#selMin");
```

Comment (PromoFaux) [reply scripts/pi-hole/js/footer.js:137]: Ultimate lazy way to add a change.

**Review by DL6ER — APPROVED** [review]
