### PR TITLE
Include FTL's DNS port in web status and give the temperature its own line

### LINKED ISSUE #2030: Admin interface reports "DNS Service not running" when pihole-FTL runs on a non-standard port.
### Versions

 - Pi-hole version is v5.6 (Latest: v5.6)
 - AdminLTE version is v5.8 (Latest: v5.8)
 - FTL version is v5.11 (Latest: v5.11)

### Platform

- OS and version:  Debian 11

- Platform:  VPS

### Expected behavior

I expect the admin interface to report the DNS Service (pihole-FTL) to be running, when it is in fact running and functioning.

### Actual behavior / bug

The admin interface reports "DNS service not running" under Status in the side-menu.

### Steps to reproduce

*Change pihole-FTL to run on a non-standard port (something not port 53).*
1) Open `/etc/dnsmasq.d/01-pihole.conf`
2) Add the line `port=12345` in the config.
3) Restart the pihole-FTL service (`# systemctl restart pihole-FTL`)

## Debug Token

- URL:  

**N/A**

### Screenshots
image

### Additional context
Issue occurs on [line 319](https://github.com/pi-hole/pi-hole/blob/master/pihole#L319) of the pihole script where it's checked if the service is listening on port 53 instead of checking if the service is running.

### PR DESCRIPTION
**Pull request by yubiuser**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Reports if FTL is running on another port than 53 in the user-panel in the web interface. Additionally, the temperature info got its own line in the user-panel

Fixes #2030

Needs: https://github.com/pi-hole/pi-hole/pull/4485

Bildschirmfoto zu 2021-12-26 18-25-01

### CODE REVIEW

File: scripts/pi-hole/php/header.php [hunk 1]
```diff
@@ -337,34 +330,31 @@ function pidofFTL()
...
                             echo '<span id="status"><i class="fa fa-circle text-green-light"></i> Active</span>';
                         } elseif ($pistatus === "0") {
                             echo '<span id="status"><i class="fa fa-circle text-red"></i> Offline</span>';
                         } elseif ($pistatus === "-1") {
                             echo '<span id="status"><i class="fa fa-circle text-red"></i> DNS service not running</span>';
+                        } elseif ($pistatus === "-2") {
+                            echo '<span id="status"><i class="fa fa-circle text-red"></i> Unknown</span>';
                         } else {
-                            echo '<span id="status"><i class="fa fa-circle text-orange"></i> Unknown</span>';
+                            echo '<span id="status"><i class="fa fa-circle text-orange"></i> DNS service on port '; echo $pistatus; echo '</span>';
```
Comment (rdwebdesign) [inline scripts/pi-hole/php/header.php]: Please, replace this:

```php
echo '<span id="status"><i class="fa fa-circle text-orange"></i> DNS service on port '; echo $pistatus; echo '</span>';
```

with:
```php
echo '<span id="status"><i class="fa fa-circle text-orange"></i> DNS service on port ';
echo $pistatus;
echo '</span>';
```

or use concatenation.:
```php
echo '<span id="status"><i class="fa fa-circle text-orange"></i> DNS service on port '.$pistatus.'</span>';
```

Comment (rdwebdesign) [reply scripts/pi-hole/php/header.php]: Also, if "$pistatus" is defined as **null** (on line 331), the output will be:

```
<span id="status"><i class="fa fa-circle text-orange"></i> DNS service on port </span>
```

without a port. 

I think you can add ` is_null($pistatus) ` to the condition on line 339. 

Or even better. Change the line 331 to: `$pistatus = -2;`

File: scripts/pi-hole/php/header.php [hunk 2]
```diff
@@ -337,34 +330,31 @@ function pidofFTL()
...
-                                if ($celsius > $temperaturelimit) {
-                                    echo "text-red";
-                                }
-                                else
-                                {
-                                    echo "text-vivid-blue";
-                                }
-                                ?>"></i> Temp:&nbsp;<span id="rawtemp" hidden><?php echo $celsius;?></span><span id="tempdisplay"></span></span><?php
+                        ?>
+                      <br/>
```
Comment (svc-user) [inline scripts/pi-hole/php/header.php:352]: There seem to have snuck an extra linebreak in, that leaves a gap in the ui.
image
image

Comment (yubiuser) [reply scripts/pi-hole/php/header.php:352]: Thanks for your comment. The issue here is not the new linebreak, but that Pi-hole was unable to find/read a temp sensor on your machine. `$celsius` is therefore set to `-273,16` and the following if condition is never met. I added an else condition which should bring back the fire symbole with the small  notice. Please try again after `pihole -up`

Comment (svc-user) [reply scripts/pi-hole/php/header.php:352]: Looking good 👍

Comment (svc-user) [reply scripts/pi-hole/php/header.php:352]: Actually, you seem to have removed the [pidofFTL](https://github.com/pi-hole/AdminLTE/blob/193fb7fcb9daff08eae5b48ab9895dd35bff4233/scripts/pi-hole/php/header.php#L153) function in the `header.php` script, which sets the `$FTL` variable that's later used to show info about pihole-FTL in the [Settings.php](https://github.com/pi-hole/AdminLTE/blob/193fb7fcb9daff08eae5b48ab9895dd35bff4233/settings.php#L235) script. My System settings tab reports FTL is not running with this branch.

**Review by DL6ER — CHANGES_REQUESTED** [review]
```
echo "<span id=\"temperature\"><i class=\"fa fa-fire ";
```
is now duplicated code. I'd rather put the `if ($celsius >= -273.15) {` further down to reduce duplication. Unfortunately, Github doesn't support suggestions if there are also lines deleted in a segment.

I imagine something like
``` php
<?php $tempcolor = "text-vivid-blue";
if ($celsius > $temperaturelimit) {
    $tempcolor = "text-red";
?><span id="temperature"><i class="fa fa-fire <? echo $tempcolor; ?>"></i> 
<?php if ($celsius >= -273.15) { ?>
  Temp:&nbsp;<span id="rawtemp" hidden><?php echo $celsius;?></span><span id="tempdisplay"></span>
<?php } else ?>
  No temp sensor found<span id="tempdisplay"></span>
<?php } ?></span>
```
(give or take some typos maybe)

File: scripts/pi-hole/php/header.php (hunk 2 above)
Comment (yubiuser) [reply scripts/pi-hole/php/header.php:352]: Good catch!
I forgot that this is used in Settings.php. Re-added it. Will push later after addressing DL6ER's comment.

File: scripts/pi-hole/php/header.php [hunk 3]
```diff
@@ -337,36 +337,29 @@ function pidofFTL()
...
                             echo '<span id="status"><i class="fa fa-circle text-green-light"></i> Active</span>';
                         } elseif ($pistatus === "0") {
                             echo '<span id="status"><i class="fa fa-circle text-red"></i> Offline</span>';
                         } elseif ($pistatus === "-1") {
                             echo '<span id="status"><i class="fa fa-circle text-red"></i> DNS service not running</span>';
+                        } elseif ($pistatus === "-2" || is_null($pistatus)) {
+                            echo '<span id="status"><i class="fa fa-circle text-red"></i> Unknown</span>';
                         } else {
-                            echo '<span id="status"><i class="fa fa-circle text-orange"></i> Unknown</span>';
+                            echo '<span id="status"><i class="fa fa-circle text-orange"></i> DNS service on port '.$pistatus.'</span>';
```
Comment (DL6ER) [inline scripts/pi-hole/php/header.php:349]:
```suggestion
                            echo '<span id="status"><i class="fa fa-circle text-orange"></i> DNS service on port '.intval($pistatus).'</span>';
```
Just is case ... This avoids presentation of possibly dangerous code if something failed down the line and $pistatus contains any kind of string.

It'd be even better to have this change further up (you cannot add a suggestion to unchanged code) at
``` PHP
$pistatus = intval($pistatus[0]);
```
and fix the remainder of the code to check for integers.

File: scripts/pi-hole/php/header.php [hunk 4]
```diff
@@ -326,7 +326,7 @@ function pidofFTL()
             <!-- Sidebar user panel -->
             <div class="user-panel">
                 <div class="pull-left image">
-                    <img src="img/logo.svg" alt="Pi-hole logo" width="45" height="67" style="height: 67px;">
+                    <img src="img/logo.svg" alt="Pi-hole logo" width="45" height="67" style="height: 90px;">
```
Comment (DL6ER) [inline scripts/pi-hole/php/header.php]: Why is the logo resized in height, is the aspect ratio still preserved?

When you want to do this, also edit the HTML height:
```suggestion
                    <img src="img/logo.svg" alt="Pi-hole logo" width="45" height="90" style="height: 90px;">
```

**Review by DL6ER — DISMISSED** [review]

File: scripts/pi-hole/php/header.php (hunk 4 above)
Comment (rdwebdesign) [reply scripts/pi-hole/php/header.php]: @DL6ER 
The logo height is the only height affecting the parent (`.user-panel`) size, because the other `<div>` child has `position: absolute`.
I have a solution, but I'm waiting this PR to finish first.

**Note:** the image is a SVG, so the aspect-ratio is preserved.

Comment (DL6ER) [reply scripts/pi-hole/php/header.php]: Now that I tried it myself, I see that the change was necessary as the temperature got its own line to make room for a possible long custom port text. It wasn't clear to me from the PR description or comments why this was needed. Now that I see it, I realize it was implicitly there in the screenshot.

**Comment by DL6ER** [comment]
I will test this once my review comments on the core PR have been discussed.

**Comment by rdwebdesign** [comment]
From my point of view, this is fine.

**Comment by yubiuser** [comment]
@bdoner 

We added a new FTL API endpoint to query for the DNS port. If you want to continue to test, please run

`pihole checkout ftl new/telnet-dns-port`

**Review by DL6ER — DISMISSED** [review]
ezgif-2-f027916d4e

The icons should be optimized to get class `fa-w` and more padding but this is another thing for a follow-up PR. T think @rdwebdesign is already at it.

File: scripts/pi-hole/php/header.php [hunk 5]
```diff
@@ -326,47 +326,40 @@ function pidofFTL()
...
                         <?php
                         $pistatus = pihole_execute('status web');
                         if (isset($pistatus[0])) {
-                            $pistatus = $pistatus[0];
+                            $pistatus = intval($pistatus[0]);
                         } else {
                             $pistatus = null;
                         }
-                        if ($pistatus === "1") {
+                        if ($pistatus == "53") {
```
Comment (DL6ER) [inline scripts/pi-hole/php/header.php]:
```suggestion
                        if ($pistatus == 53) {
```

File: scripts/pi-hole/php/header.php [hunk 6]
```diff
@@ -326,47 +326,40 @@ function pidofFTL()
...
                             echo '<span id="status"><i class="fa fa-circle text-green-light"></i> Active</span>';
-                        } elseif ($pistatus === "0") {
+                        } elseif ($pistatus == "0") {
```
Comment (DL6ER) [inline scripts/pi-hole/php/header.php]:
```suggestion
                        } elseif ($pistatus == 0) {
```

File: scripts/pi-hole/php/header.php [hunk 7]
```diff
@@ -326,47 +326,40 @@ function pidofFTL()
...
                             echo '<span id="status"><i class="fa fa-circle text-red"></i> Offline</span>';
-                        } elseif ($pistatus === "-1") {
+                        } elseif ($pistatus == "-1") {
```
Comment (DL6ER) [inline scripts/pi-hole/php/header.php]:
```suggestion
                        } elseif ($pistatus == -1) {
```

File: scripts/pi-hole/php/header.php [hunk 8]
```diff
@@ -326,47 +326,40 @@ function pidofFTL()
...
                             echo '<span id="status"><i class="fa fa-circle text-red"></i> DNS service not running</span>';
+                        } elseif ($pistatus == "-2" || is_null($pistatus)) {
```
Comment (DL6ER) [inline scripts/pi-hole/php/header.php]:
```suggestion
                        } elseif ($pistatus == -2 || is_null($pistatus)) {
```

**Review by DL6ER — COMMENTED** [review]
`$pistatus` is never a string

**Review by DL6ER — APPROVED** [review]

**Comment by rdwebdesign** [comment]
> The icons should be optimized to get class `fa-w` and more padding but this is another thing for a follow-up PR. T think @rdwebdesign is already at it.

I will look at this after the completion of #2031.

**Comment by DL6ER** [comment]
@yubiuser Feel free to merge if you are fine with my latest changes.
