### PR TITLE
charts.js: refactor to reduce complexity, improve readability and per…

### LINKED ISSUE #3531: Cache pie-chart legend underlined
### Expected behavior

No underlining when hovering over unclickable text.

### Actual behavior / bug

The DNS query types in the Cache pie-chart legend become underlined when hovered over, such as `CNAME` in the screenshot below. 
(Unlike similar pie-charts on the dashboard, the query types here are not clickable, so should probably not get an underline).

### Steps to reproduce

Mouse over the DNS query types beside the cache pie chart.

## Debug Token
n/a

### Screenshots

Image

### PR DESCRIPTION
**Pull request by XhmikosR**
…formance

Also

* drop jQuery usage
* move inline styles to CSS when possible
* switch to `a` tags for links otherwise use `p`

Split from #3534. Note that this is just the first patch for now. The file is tweaked further later.

Should take care of the changes of #3532 too.

Fixes #3531.

---

## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

**How does this PR accomplish the above?:**

**Link documentation PRs if any are needed to support this PR:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by XhmikosR** [comment]
Note that I also have this patch https://github.com/XhmikosR/web/commit/afed0c392637fdb8c2cf4e44d33d863088178184, but I can't cherry pick it here. I will do it later after we address my other PRs and we get to that patch.

File: scripts/js/charts.js [hunk 1]
```diff
@@ -29,121 +28,92 @@ const THEME_COLORS = [
...
-        ? '<i class="colorBoxWrapper fa fa-square"></i>'
-        : '<i class="colorBoxWrapper fa fa-check-square"></i>';
+      boxSpan.innerHTML = `<i class="colorBoxWrapper fa ${item.hidden ? "fa-square" : "fa-check-square"}"></i>`;
 
       boxSpan.addEventListener("click", () => {
         const { type } = chart.config;
+        const isPieOrDoughnut = type === "pie" || type === "doughnut";
 
-        if (type === "pie" || type === "doughnut") {
+        if (isPieOrDoughnut) {
```
Comment (PromoFaux) [inline scripts/js/charts.js:76]: I don't really understand the need to take a simple if conditional and put it's value into a const, especially whne that value is not used anywhere else - why does it need to be a const?

Is this some new trend I have missed?

Seems to have been done a lot in this file, and I don't _overly_ understand what is gained from it

File: scripts/js/charts.js [hunk 2]
```diff
@@ -152,169 +122,217 @@ const customTooltips = function (context) {
...
 
-  const canvasPos = this.chart.canvas.getBoundingClientRect();
+  tooltipHtml += "</tbody>";
+
+  const tableRoot = tooltipEl.querySelector("table");
+  tableRoot.innerHTML = tooltipHtml;
+}
+
+function positionTooltip(tooltipEl, tooltip, context) {
+  if (tooltip.opacity === 0 || tooltipEl.style.opacity === 0) return;
```
Comment (PromoFaux) [inline scripts/js/charts.js:219]: Yet sometimes it seems we are allowed to just do classic simple if statements

If we're doing it above, why doesn't this line have something like `const isTooltipOpaque = (tooltiip.opacity.......` above it?

File: scripts/js/charts.js [hunk 3]
```diff
@@ -152,169 +122,217 @@ const customTooltips = function (context) {
...
+      case "center": {
+        tooltipX -= tooltipWidth / 2;
+        break;
+      }
+      // No default
     }
+  }
 
+  // Adjust X position if tooltip is centered inside ancestor
+  if (document.documentElement.clientWidth <= 2 * tooltip.width && tooltip.xAlign === "center") {
```
Comment (PromoFaux) [inline scripts/js/charts.js:281]: and here.

Note - I'm not suggesting that it should be one way or the other, but it should be...consistent.

File: scripts/js/charts.js [hunk 4]
```diff
@@ -152,169 +122,217 @@ const customTooltips = function (context) {
...
-          if (2 * tooltipX < tooltipWidth + minX) {
-            arrowX = tooltipX - minX;
-            tooltipX = minX;
-          } else {
-            tooltipX -= tooltipWidth / 2;
-          }
-
-          break;
-        }
+  if (tooltip.yAlign === "top" || tooltip.yAlign === "bottom") {
```
Comment (PromoFaux) [inline scripts/js/charts.js:236]: Same thing here

**Review by PromoFaux — COMMENTED** [review]
Confusion

File: scripts/js/charts.js (hunk 1 above)
Comment (XhmikosR) [reply scripts/js/charts.js:76]: This is gone later but I can't cherry pick it as it is now. I started the refactoring with this first patch and then made https://github.com/XhmikosR/web/commit/afed0c392637fdb8c2cf4e44d33d863088178184 along the way. Unfortunately, in order to pick the next patch I need to land others first which I can't do it here.

File: scripts/js/charts.js (hunk 2 above)
Comment (XhmikosR) [reply scripts/js/charts.js:219]: No need to do have it as a separate statement. The reason I did it in the first place is that I expected more cases in the if statement. This one is not long enough, so I used it directly. Not something really important to argue about IMHO :)

File: scripts/js/charts.js (hunk 1 above)
Comment (PromoFaux) [reply scripts/js/charts.js:76]: Well then - lets wait until such time as those changes can be cherry-picked into here. No point in merging changes taht are then just going to be overwritten

Comment (XhmikosR) [reply scripts/js/charts.js:76]: That's impossible... I try to move the changes from #3534 in parts. I cannot rewrite the whole branch and you guys probably cannot review #3534 as is. Although Mostly 2 patches are big there.

**Review by PromoFaux — APPROVED** [review]

**Comment by yubiuser** [comment]
This does not fix https://github.com/pi-hole/web/issues/3531.

Peek 2025-07-12 08-50

**Comment by XhmikosR** [comment]
I'll have a look again when I'm back at my desktop. Thanks for letting me
know.

**Comment by XhmikosR** [comment]
So, looking at it from my cell phone it's this patch that fixes this
https://github.com/XhmikosR/web/commit/9f0d9b31797c95186387621cdaa3e828348dde8c?w=1

The problem is that is not cherry pickable against development. I suggest
we wait a little bit more to prevent extraneous conflicts as we are getting
close to landing the big patches from that branch.

Otherwise, if it takes too long I'll manually redo this patch against the
development branch.
