### PR TITLE
Changing the information source to "pi-hole status" in the API

### LINKED ISSUE #1965: API reporting status: enabled while blocking is disabled
### Versions
- Pi-hole:  5.6
- AdminLTE:  5.11
- FTL:  5.8

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster)
- Platform:  Raspberry Pi Zero W

### Expected behavior

When disabling the Pi-hole (through the API) I would expect the API to return `"status": disabled`. The dashboard is showing the status correctly.

### Actual behavior / bug

When disabling the Pi-hole (through the API or through the web interface), the API is reporting `"status": enabled` while the dashboard is showing the status 'disabled' correctly.

### Steps to reproduce

1. Disable blocking
2. Look at the web interface and the response at http://[IP]/admin/api.php?summaryRaw

## Debug Token

- URL:  https://tricorder.pi-hole.net/Q1SX7zAi/

### Screenshots

image

### Additional context

I notice this problem with users of my iOS app (Pi-hole Remote) and am now noticing it for the first time myself. It happens on my freshly installed Pi Zero W, but not on a freshly installed Pi 4.

### PR DESCRIPTION
**Pull request by rdwebdesign**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Fix an API intermittent error, where the status info received by `api.php` or `api.php?summary` is sometimes wrongly reported.
Cause: 
`api_FTL.php` uses FTL response to determine if pi-hole is _enabled_ or _disabled_. 
FTL only updates this value when is internally needed, but it doesn't update this value before answering the API call. 
  
**How does this PR accomplish the above?:**

Replacing the status received from FTL with the status currently stored in `setupVars.conf`.

**What documentation changes (if any) are needed to support this PR?:**

none

### CODE REVIEW

**Comment by yubiuser** [comment]
Idea: Re-use

https://github.com/pi-hole/AdminLTE/blob/33755f1775db31bc5cd5de0f8d82fa10a000bd42/api.php#L23-L41

**Comment by DL6ER** [comment]
> Idea: Re-use
> 
> https://github.com/pi-hole/AdminLTE/blob/33755f1775db31bc5cd5de0f8d82fa10a000bd42/api.php#L23-L41

This is a good idea. Refactor this into its own function and use the same functions in both. Prevents this from happening again in the future.

**Comment by rdwebdesign** [comment]
I think I will reuse my new function:

This: 
```php
if (isset($_GET['status'])) {
    // Receive the return of "pihole status web"
    $pistatus = pihole_execute('status web');

    if (isset($pistatus[0])) {
        $pistatus = intval($pistatus[0]);
    } else {
        // If no response, status="Unknown" (-2)
        $pistatus = -2;
    }

    switch ($pistatus) {
        case -2: // Unkown
        case -1: // DNS service not running"
        case 0: // Offline
            $data = array_merge($data, array("status" => "disabled"));
            break;

        default:
            // DNS service on port $returncode
            $data = array_merge($data, array("status" => "enabled"));
    }

} elseif ...
```

Will become this:
```php
if (isset($_GET['status'])) {
    // read setupVars and return the status
    $data = array_merge($data, array("status" => piholeStatus() ));

} elseif ... 
```

What do you think?

**Comment by yubiuser** [comment]
Just reading `/etc/pihole/setupVars.conf` is not enough. When blocking is enabled there, but FTL is not running, we should not return `status=enabled` We actually need to check if FTL is running before determining the blocking status,

File: scripts/pi-hole/php/func.php [hunk 1]
```diff
@@ -483,4 +483,15 @@ function getQueryTypeStr($querytype)
         return "TYPE".($qtype - 100);
 }
 
+// Returns the blocking status of pihole
+function piholeStatus()
+{
+    $setupVars = parse_ini_file("/etc/pihole/setupVars.conf");
+    if ($setupVars["BLOCKING_ENABLED"]=="1") {
```
Comment (yubiuser) [inline scripts/pi-hole/php/func.php]: We do use `true/false` literally here
https://github.com/pi-hole/pi-hole/blob/363e2f10bb4f3717055a84c42954ca2b3bde1744/pihole#L225-L240

**Comment by DL6ER** [comment]
So the question is `pihole status web` or reading `setupVars.conf` using `parse_ini_file()`

What happens if there are comments in setupVars.conf ?

**Comment by rdwebdesign** [comment]
> Just reading `/etc/pihole/setupVars.conf` is not enough. When blocking is enabled there, but FTL is not running, we should not return `status=enabled` We actually need to check if FTL is running before determining the blocking status,

I didn't know it was possible to have `status=enabled` in `setupVars.conf` while FTL is not running

**Comment by yubiuser** [comment]
It could just crash...

**Comment by rdwebdesign** [comment]
> What happens if there are comments in setupVars.conf ?

PHP strips the comments.

File: scripts/pi-hole/php/func.php (hunk 1 above)
Comment (rdwebdesign) [reply scripts/pi-hole/php/func.php]: I used this code in a new function.

Now, we have 2 functions:
- piholeStatusAPI(): returns "enabled" or "disabled";
- piholeStatus(): returns an integer representing the status.

PS: You can use this new `piholeStatus()` function on the status panel code.

**Review by yubiuser — APPROVED** [review]
Works both for `http://pi.hole/admin/api.php` and `http://pi.hole/admin/api.php?status`
