### PR TITLE
Include timezone info in time/date FTL has been started

### LINKED ISSUE #1025: "Time FTL started" does not honour timezone
"Time FTL started" does not honour timezone

This is a... 

- [ ] Request for a new or modified feature
- [x] Issue trying to run the docker image
- [ ] Issue trying to build / test / develop the docker image

## Description

The docker images runs with timezone 'Europe/Berlin' via TZ environment variable. 
The settings->system page does not honour the timezone for "Time FTL started". Time is always UTC.

## Expected Behavior

Time is displayed with correct timezone.

## Actual Behavior

Always show UTC time.

## Steps to Reproduce and debugging done

e.g. your docker run command, pages to visit, CLI commands you ran
1. Create container with TZ: 'Europe/Berlin'.
2. Check TZ in running container with
   ```
   # docker exec -ti pihole bash
   root@9fa8a12ef3a1:/# echo $TZ
   Europe/Berlin```
3.  Load Pi-Hole admin page -> settings -> system

## Debug steps I have tried
<!-- Please attempt these debug steps to see if it helps you resolve or understand your own issue -->

- [x] I have tried destroying my container instance, pulling the newest image version, and re-creating a new container
- [ ] I have tried running the nearly stock `docker run` example in the readme (removing any customizations I added)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause
- [x] I have searched this repository for existing issues and pull requests that look similar <!-- Add links below! -->

<!-- Note: If volumes are your issue, I strongly recommend just starting with fresh volume data -->

<!-- Add any other debugging steps you've taken that maybe relevant information -->

## Context and extra information
<!-- How has this bug affected you? What were you trying to accomplish? -->
<!-- Got any other relevant links to similar issues? -->

## Your Environment 
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Docker Host Operating System and OS Version: Fedora 30
* Docker Version: Docker version 1.13.1, build 47e2230/1.13.1 (Fedora Repo)
* Hardware architecture: x64
* Pi-hole Version v4.3.2 Web Interface Version v4.3.2 FTL Version v4.3.1

### PR DESCRIPTION
**Pull request by yubiuser**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Include the local timezone in the "FTL started" date/time output
Bildschirmfoto zu 2022-02-05 17-10-26

**How does this PR accomplish the above?:**

Included a check for the ENV "TZ" which can be used by docker installations. If not present, I use the time zone output of date.

### CODE REVIEW

File: settings.php [hunk 1]
```diff
@@ -240,6 +240,7 @@ function get_FTL_data($arg)
                                                 }
 
                                                 $FTLversion = exec("/usr/bin/pihole-FTL version");
+																								$FTLstart = exec("date -r /proc/" . $FTLpid . " '+%a %d %b %Y %R %Z'");
```
Comment (rdwebdesign) [inline settings.php]: Just a note:

The indentation is weird.
I think you used `tabs` to indent you code, but the rest of the code is using `spaces`.

Comment (yubiuser) [reply settings.php]: Fixed.

See: https://github.com/pi-hole/AdminLTE/issues/1983

**Review by DL6ER — DISMISSED** [review]
They don't seem equivalent
```
pi@ubuntu-server:~$ ps -p $(pidof pihole-FTL) -o lstart
                 STARTED
Wed Feb  2 21:24:50 2022

pi@ubuntu-server:~$ date -r /proc/$(pidof pihole-FTL)
Fri 04 Feb 2022 05:39:01 PM CET
```

Looking at the logs, the last restart was indeed on Feb 2nd.

**Comment by rdwebdesign** [comment]
https://github.com/pi-hole/docker-pi-hole/pull/996 fixed the time.

If you still want to include the time zone, you can append `." ".getenv("TZ")` to the time output.

**Comment by yubiuser** [comment]
Thanks for your suggestion. I included a check for the ENV "TZ" which can be used by docker installations. If not present, I use the time zone output of `date`.

As `date` of the `/proc/PID` seems unreliable, I switched back to `ps`

File: settings.php [hunk 2]
```diff
@@ -19,6 +19,12 @@
 	$error .= "There was a problem applying your settings.<br>Debugging information:<br>PHP error (".htmlspecialchars($last_error["type"])."): ".htmlspecialchars($last_error["message"])." in ".htmlspecialchars($last_error["file"]).":".htmlspecialchars($last_error["line"]);
 }
 
+# Timezone is set in docker via ENV otherwise get it from commandline
+$timezone=getenv("TZ");
```
Comment (rdwebdesign) [inline settings.php]: You are right.
When I suggested the code, I forgot the non-docker installs.

Use:

```php
$timezone = date_default_timezone_get();
```

Comment (yubiuser) [reply settings.php]: If I interpret https://www.php.net/manual/en/function.date-default-timezone-get.php correclty, one needs `date_default_timezone_set()` or set a TZ via `date.timezone ini option` for `date_default_timezone_get` to return anything else then `UTC` but we do not set one of the two options, or?

Comment (rdwebdesign) [reply settings.php]: Hummm... Maybe. I can test it now.

Comment (rdwebdesign) [reply settings.php]: Forget my suggestion and use the current code.

**Review by DL6ER — APPROVED** [review]
