### PR TITLE
1119 Privacy - Query Page and Dom.storage

### LINKED ISSUE #1119: Privacy - Query Page and Dom.storage
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{5}`

---
**Expected behaviour:**

`{The query page should work with dom.storage disabled. Dom.storage can be used in many manipulative ways to track users cross-site and across devices. Users who have dom.storage disabled should also have a way to view the query page. }`

**Actual behaviour:**

`{The part of the code where the issue stems from can be trivially located using the Developer Console. Users who disable dom.storage are unable to see anything on the query page. This is how it looks like if you disable dom.storage in Firefox: }`
[Imgur](https://i.imgur.com/kvFx2Ra.png)

**Steps to reproduce:**

`{This applies only to Firefox: 1) Go to: about:config. 2) Set: dom.storage.enabled to false. 3) Go to the query page of your pi.hole}`

**Troubleshooting undertaken, and/or other relevant information:**
I know that this isn't technically an issue, but rather an improvement. If it can changed by the pi.hole team without extensive effort, then I'm sure a small subset of users would welcome it. Right now one is forced to either be blind in the query log or have dom.enabled (former is an inconvenience (except when you want to figure out why some website isn't working), later is a huge privacy risk).

Thank you for all the work so far.

### PR DESCRIPTION
**Pull request by chrismiceli**
handle localStorage being null

Signed-off-by: Chris Miceli <chrismiceli@outlook.com>

**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**
Addresses https://github.com/pi-hole/AdminLTE/issues/1119

**How does this PR accomplish the above?:**
This PR defaults all storage access to as if the item wasn't present to allow execution of scripts to continue. Note that I left some cases where a user interacts with a setting so that there is an indication the preference/setting wasn't persisted.

**What documentation changes (if any) are needed to support this PR?:**
None, unless we want to officially document when storage is disabled.

### CODE REVIEW

File: scripts/pi-hole/js/settings.js [hunk 1]
```diff
@@ -334,15 +334,17 @@ $(".nav-tabs a").on("shown.bs.tab", function (e) {
...
   } else {
     // Initialize checkbox
     bargraphs.prop("checked", true);
-    localStorage.setItem("barchart_chkbox", true);
+    if (localStorage) {
+      localStorage.setItem("barchart_chkbox", true);
+    }
   }
 
   bargraphs.click(function () {
```
Comment (chrismiceli) [inline scripts/pi-hole/js/settings.js:350]: note that I left the click functions for settings a storage object unguarded so there is a console error message to indicate the saving failed. I guarded initialization routines that set storage to prevent further code running during initialization from getting blocked.

**Review by PromoFaux — DISMISSED** [review]

**Review by yubiuser — COMMENTED** [review]
What's about L233 in`utils.js`?

```
function stateSaveCallback(itemName, data) {
  localStorage.setItem(itemName, JSON.stringify(data));
}
```
I tried your PR locally and I wasn't able to display the query log in FF with dom.stroage=disabled. I got errors about `stateSaveCallback`

**Comment by chrismiceli** [comment]
> What's about L233 in`utils.js`?
> 
> ```
> function stateSaveCallback(itemName, data) {
>   localStorage.setItem(itemName, JSON.stringify(data));
> }
> ```
> 
> I tried your PR locally and I wasn't able to display the query log in FF with dom.stroage=disabled. I got errors about `stateSaveCallback`

I intentionally left the modification methods untouched so that the user could see an error in the console about why their settings are not being persisted in storage. I could log a more specific message in those cases.

Let me see why query log isn't loading.

**Comment by chrismiceli** [comment]
> > What's about L233 in`utils.js`?
> > ```
> > function stateSaveCallback(itemName, data) {
> >   localStorage.setItem(itemName, JSON.stringify(data));
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried your PR locally and I wasn't able to display the query log in FF with dom.stroage=disabled. I got errors about `stateSaveCallback`
> 
> I intentionally left the modification methods untouched so that the user could see an error in the console about why their settings are not being persisted in storage. I could log a more specific message in those cases.
> 
> Let me see why query log isn't loading.

I pushed a commit @yubiuser to address the query log not loading. I now use a memory storage mechanism which won't survive page loads but enables callbacks to trigger correctly.

File: scripts/pi-hole/js/utils.js [hunk 2]
```diff
@@ -229,13 +229,20 @@ function setBsSelectDefaults() {
...
+  } else {
+    localStorage.setItem(itemName, JSON.stringify(data));
+  }
 }
 
 function stateLoadCallback(itemName) {
   // Receive previous state from client's local storage area
-  var data = localStorage.getItem(itemName);
+  var data =
+    localStorage === null ? backupStorage[itemName] || null : localStorage.getItem(itemName);
```
Comment (rdwebdesign) [inline scripts/pi-hole/js/utils.js]: I don't read all your code, but this part
```js
backupStorage[itemName] || null
```
will convert `0` (zero) and `''` (empty string) to `null`.

Is this the intended behavior?

Comment (chrismiceli) [reply scripts/pi-hole/js/utils.js]: Great comment. I pushed a commit to be explicit for undefined to not convert those to null.

File: scripts/pi-hole/js/utils.js [hunk 3]
```diff
@@ -239,9 +239,14 @@ function stateSaveCallback(itemName, data) {
...
 function stateLoadCallback(itemName) {
+  var data;
   // Receive previous state from client's local storage area
-  var data =
-    localStorage === null ? backupStorage[itemName] || null : localStorage.getItem(itemName);
+  if (localStorage === null) {
+    var item = backupStorage[itemName];
+    data = typeof item === "undefined" ? null : item;
+  } else {
+    localStorage.getItem(itemName);
```
Comment (rdwebdesign) [inline scripts/pi-hole/js/utils.js]: I think you mean:
```js
  } else {
    data = localStorage.getItem(itemName);
  }
```

Comment (chrismiceli) [reply scripts/pi-hole/js/utils.js]: Of course. This is what happens when I rush :(. I pushed a commit to resolve.

**Comment by rdwebdesign** [comment]
> Of course. This is what happens when I rush :(. I pushed a commit to resolve.

It happens to anyone. No need to rush.
Take your time and test the code, if needed.

**Comment by yubiuser** [comment]
Confirm query log is working now.

**Review by rdwebdesign — APPROVED** [review]
