### PR TITLE
Limit MAXLOGAGE to 24h, just like FTL  

### LINKED ISSUE #1825: Bar graphs on main admin page state 72 hours but each shows only 24
### Versions

- Pi-hole:  v5.3.1 (Latest: v5.3.1)
- AdminLTE:  v5.5 (Latest: v5.5)
- FTL:  v5.8.1 (Latest: v5.8.1)

### Platform
- OS and version: Raspbian GNU/Linux 10 (buster) _[Debian variant]_
> Linux pihole-mark0mod0 5.10.17-v7l+ 1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
- Platform:  Raspberry Pi

### Expected behavior

At http://pi.hole/admin/index.php, there are two headings:

> Total queries over last **72 hours**
> Client activity over last **72 hours**

Each has a graph below it, but the graphs are labeled to **only show 24 hours of data**.

1. The _heading_ of the graph should match the _content_ of that graph

### Actual behavior / bug

1. Only 24 hours of data appear to be shown, while the heading promises 72

Either:

- the graphs should be changed to match the heading, or
- the headings (or other text) should be updated to clarify what is being shown
  - e.g., depending on what data is actually intended to be presented to the viewer:
    - "Total queries over last 24 hours"
    - "Queries for each 10-minute period during the past 24 hours"
    - "Total queries over last 24 hours (for each 10-minute period)"
    - "Total queries per time period"
    - "Total queries over last 72 hours (aggregated for each time period in a single day)"
    - "Average queries over last 72 hours (averaged over each time period)"

### Steps to reproduce

1. View the page at http://pi.hole/admin/index.php

## Debug Token

- URL:  https://tricorder.pi-hole.net/ugcs0vb9au

### Screenshots

image

### Additional context

After I started this, I thought, "perhaps the graph is _actually_ showing either the average or total number requests *of each time period* but across three days". 

This _does not seem to be the case,_ however, since when viewing the query log by clicking on a time period bar, only the queries from the most recent occurrence of that time period are shown.

### PR DESCRIPTION
**Pull request by rdwebdesign**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

**What does this PR aim to accomplish?:**

Fix #1825.

If `MAXLOGAGE` is set inside _pihole-FTL.conf_ to anything greater than 24, it is already limited by FTL (and the graphic is limited to 24 hours), but the graphic title shown on the dashboard is using the wrong (not limited) value.

**How does this PR accomplish the above?:**

Limiting the interval for the dashboard graphic title to a maximum of 24 hours, since FTL already limits this value.

**What documentation changes (if any) are needed to support this PR?:**

I think this was already changed in the docs.

### CODE REVIEW

File: index.php [hunk 1]
```diff
@@ -1,26 +1,24 @@
-<?php /*
+<?php
+/*
```
Comment (PromoFaux) [inline index.php]: I know it's different in other files, too, but as you've made a change here, can you make it like it is in `api_db.php` please? 

https://github.com/pi-hole/AdminLTE/blob/master/api_db.php#L2

```
/*   Pi-hole: A black hole for Internet advertisements
```

Comment (rdwebdesign) [reply index.php]: Done

**Review by yubiuser — APPROVED** [review]
