### PR TITLE
Status search

### LINKED ISSUE #2: Filter Status field not working
In http://web.pi-hole.io/#/query-log is possible filter out records. But Status field doesnt work. Expecting that i can filter out blocked domains only when i write "Blocked" there.

### PR DESCRIPTION
**Pull request by JayCGildea**
**What does this PR aim to accomplish?:**
Allowing users to search using text in the query log, rather than the current number system. Fixes #2.

**How does this PR accomplish the above?:**
Adds a const for the status in query log. Uses this for display and a custom filter has been added to fetch the string from this before comparing with the filter text.

### CODE REVIEW

File: src/components/QueryLog.js [hunk 1]
```diff
@@ -104,26 +112,17 @@ const columns = [
...
+      id: "status",
+      accessor: r => r[4],
+      width: 140,
+      Cell: row => status[row.value],
+      filterMethod: (filter, row) =>
+        status[row[filter.id]]
+          .toLowerCase()
+          .includes(
+            filter.value.toLowerCase()
+          )
```
Comment (Mcat12) [inline src/components/QueryLog.js]: You added an extra indentation, but otherwise it looks good.

**Comment by JayCGildea** [comment]
Sorry - I managed to turn notifications off. I'll change it later today
