### PR TITLE
Remove HTML from titles when not needed.

### LINKED ISSUE #1457: HTML code visible in tooltip in black/whitelist
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

No HTML in tooltip.

**Actual behaviour:**

HTML in tooltip.

Bildschirmfoto zu 2020-06-12 10-40-43

**Steps to reproduce:**

  AdminLTE version is devel v5.0-387-g557bd858 (Latest: v5.

### PR DESCRIPTION
**Pull request by XhmikosR**
**By submitting this pull request, I confirm the following:** `{please fill any appropriate checkboxes, e.g: [X]}`

`{Please ensure that your pull request is for the 'devel' branch!}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
- [x] I have Signed Off all commits. ([`git commit --signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff))

---

Should fix #1457. **Untested**.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Do note that we could alternatively use Bootstrap's tooltip plugin which might have been the original intention.

**Comment by yubiuser** [comment]
Works.
Bildschirmfoto zu 2020-06-14 16-37-28

File: scripts/pi-hole/js/utils.js [hunk 1]
```diff
@@ -104,8 +104,9 @@ function showAlert(type, icon, title, message) {
   }
 }
 
-function datetime(date) {
-  return moment.unix(Math.floor(date)).format("Y-MM-DD [<br class='hidden-lg'>]HH:mm:ss z");
+function datetime(date, html) {
```
Comment (DL6ER) [inline scripts/pi-hole/js/utils.js:107]: Is it valid to call this function with one parameter (like `utils.datetime(data.date_added)`) here? I'm sure this is done in some places like `groups.js`.

Comment (XhmikosR) [reply scripts/pi-hole/js/utils.js:107]: Yeah, it should be fine because `html` won't be false which is the only value I check for.

Comment (XhmikosR) [reply scripts/pi-hole/js/utils.js:107]: Either way, this in untested like I said in the PR description. I will try to find some time to test it in the next days.

**Comment by DL6ER** [comment]
@XhmikosR I'm pretty sure we used Bootstrap tooltips at some point, not sure about the current status. However, I'm fine with getting them removed. While getting ready now for the nearing v5.1 release, can you test/finish this in the next days or shall we postpone it to v5.2 ?

**Comment by XhmikosR** [comment]
Sure thing, I'll take care of it tomorrow. I don't see Bootstrap tooltip being used in any page other than the settings DHCP tab.

File: scripts/pi-hole/js/utils.js [hunk 2]
```diff
@@ -104,8 +104,9 @@ function showAlert(type, icon, title, message) {
...
+  var format = html === false ? "Y-MM-DD HH:mm:ss z" : "Y-MM-DD [<br class='hidden-lg'>]HH:mm:ss z";
```
Comment (XhmikosR) [inline scripts/pi-hole/js/utils.js:108]: This works because `false !== undefined`, so if we don't pass `false` as the second parameter, the condition is false.

**Review by PromoFaux — APPROVED** [review]
Confirming this works as expected
