### PR TITLE
Set rate-limiting options from settings page

### LINKED ISSUE #1783: Settings > Privacy does not show updated as expected
### Versions
Pi-hole version is v5.3.1 (Latest: v5.3.1)
AdminLTE version is v5.5 (Latest: v5.5)
FTL version is v5.8 (Latest: v5.8)

### Platform
- OS and version:  Raspbian GNU/Linux 10 (buster) debian
- Platform:  Raspberry Pi

### Expected behavior
I visit the page Settings > Privacy (/admin/settings.php?tab=privacy)
The DNS resolver privacy level is set to Show everything and record everything
I change it to Anonymous mode and press Apply

The page should refresh and show the DNS resolver privacy level is set to Anonymous mode

### Actual behavior / bug

The page refreshes, a blue bar shows saying "Info - The privacy level has been increased" but the DNS resolver privacy level is still Show everything and record everything

When I manually refresh the page, the correct DNS resolver privacy level is showing.

The same happens in reverse.

### Steps to reproduce

As above

## Debug Token

- URL:  https://tricorder.pi-hole.net/am4g9pc59k

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Make it easier to configure rate-limiting by offerings a GUI setting.

**How does this PR accomplish the above?:**

Add the following section to Settings -> DNS -> Advanced DNS settings

Screenshot from 2022-02-19 11-00-52

Depends on https://github.com/pi-hole/pi-hole/pull/4621

**What documentation changes (if any) are needed to support this PR?:**

None

### CODE REVIEW

File: scripts/pi-hole/php/savesettings.php [hunk 1]
```diff
@@ -352,6 +352,13 @@ function addStaticDHCPLease($mac, $ip, $hostname) {
 				}
 				pihole_execute("-a -i ".$DNSinterface." -web");
 
+				// Add rate-limiting settings
+				if(isset($_POST["rate_limit_count"]) && isset($_POST["rate_limit_interval"]))
+				{
+					// Restart of FTL is delayed
+					pihole_execute("-a ratelimit " . intval($_POST["rate_limit_count"]) . " " . intval($_POST["rate_limit_interval"]) . " false");
```
Comment (yubiuser) [inline scripts/pi-hole/php/savesettings.php:359]: Why do you pass `false` here? Shut the setting not take effect immediately?

File: scripts/pi-hole/php/FTL.php [hunk 2]
```diff
@@ -8,12 +8,12 @@
 
 $piholeFTLConfFile = "/etc/pihole/pihole-FTL.conf";
 
-function piholeFTLConfig()
+function piholeFTLConfig($force=false)
```
Comment (yubiuser) [inline scripts/pi-hole/php/FTL.php:11]: I'm not sure if I understand what you are doing here with the `force` flag. What is your goal?

Comment (DL6ER) [reply scripts/pi-hole/php/FTL.php:11]: This function caches the result from reading `pihole-FTL.conf` on first read and returns the cached value on any subsequent call without re-reading.

This is a problem with the new code: We read `pihole-FTL.conf` in `savesettings.php` when saving the settings (old values), then the script calls `pihole -a rataelimit x y`. Later on, we call `piholeFTLConfig()` again but this still contains the *old* values as the function returns from cache. This new option allows us to force re-reading instead of using the cache. This fixes the issue. The `force` flag defaulting to `false` preserves the current behavior in all other places where we don't need this.

File: scripts/pi-hole/php/savesettings.php (hunk 1 above)
Comment (DL6ER) [reply scripts/pi-hole/php/savesettings.php:359]: With the current design of the settings page it is not possible to set/change the rate-limiting values alone. Only a few lines down we call `pihole -a setdns ...` which will inevitably restart FTL. No need for two restarts in a short time.

File: settings.php [hunk 3]
```diff
@@ -934,6 +947,21 @@ function convertseconds($argument)
                                                     <a href="https://dnssec.vs.uni-due.de/" rel="noopener" target="_blank">here</a>.</p>
                                                 </div>
                                                 <br>
+                                                <h4><a id="ratelimit"></a>Rate-limiting</h4>
+                                                <p>Block clients making more than <input type="number" name="rate_limit_count" value="<?=$rate_limit_count?>"> queries within
```
Comment (yubiuser) [inline settings.php]:
```suggestion
                                                <p>Block clients making more than <input type="number" name="rate_limit_count" value="<?=$rate_limit_count?>" min="0" step="10"> queries within
```

File: settings.php [hunk 4]
```diff
@@ -934,6 +947,21 @@ function convertseconds($argument)
...
+                                                <input type="number" name="rate_limit_interval" value="<?=$rate_limit_interval?>"> seconds.</p>
```
Comment (yubiuser) [inline settings.php]:
```suggestion
                                                <input type="number" name="rate_limit_interval" value="<?=$rate_limit_interval?>" min="0" step="10"> seconds.</p>
```

File: scripts/pi-hole/php/FTL.php (hunk 2 above)
Comment (yubiuser) [reply scripts/pi-hole/php/FTL.php:11]: Thanks. 

So I guess as a side effect this just fixed https://github.com/pi-hole/AdminLTE/issues/1783 as well?

**Review by yubiuser — COMMENTED** [review]
The size of the input fields look a bit off. Can you make them a bit shorter
Bildschirmfoto zu 2022-02-19 21-36-52

File: settings.php (hunk 3 above)
Comment (rdwebdesign) [reply settings.php]: If you want to limit the width of the field, add `size="6"` to the input tag (size in characters).
If you want to limit the allowed range, use `min="X" max="Y"` in the input tag.

File: scripts/pi-hole/php/FTL.php (hunk 2 above)
Comment (DL6ER) [reply scripts/pi-hole/php/FTL.php:11]: Oh yes, I didn't even see this other issue.

File: settings.php (hunk 3 above)
Comment (DL6ER) [reply settings.php]: `size="6"` doesn't change anything, the width may be given by some outer CSS. Manually forcing the width via a local CSS setting works as expected.

Comment (rdwebdesign) [reply settings.php]: Yeah... 
Apparently only Firefox respects `size` attribute. `size="6"` is not respected (by most browsers) if the type is `number`.

If you want to use `type="number"` we need to add a CSS rule.

**NOTE:**
If you add the **`max`** attribute, most browsers will resize the field to a suitable size.

Comment (DL6ER) [reply settings.php]: I don't think we can/should set a maximum. One might argue that a sensible maximum could be something like 100,000 queries over 86,400 seconds (one day) but users may want to do other things (like limiting per week) - you never know. I'd feel better without enforcing a maximum here.

Comment (DL6ER) [reply settings.php]: Addressed in the most recent commit, preview:

Screenshot from 2022-02-26 10-08-04

The query limit field is intentionally larger than the seconds field as we are expecting larger numbers here.

File: settings.php [hunk 5]
```diff
@@ -934,6 +947,21 @@ function convertseconds($argument)
                                                     <a href="https://dnssec.vs.uni-due.de/" rel="noopener" target="_blank">here</a>.</p>
                                                 </div>
                                                 <br>
+                                                <h4><a id="ratelimit"></a>Rate-limiting</h4>
+                                                <p>Block clients making more than <input type="number" name="rate_limit_count" value="<?=$rate_limit_count?>" min="0" step="10" style="width: 5em;"> queries within
+                                                <input type="number" name="rate_limit_interval" value="<?=$rate_limit_interval?>" min="0" step="10" style="width: 3em;"> seconds.</p>
```
Comment (yubiuser) [inline settings.php]:
```suggestion
                                                <input type="number" name="rate_limit_interval" value="<?=$rate_limit_interval?>" min="0" step="10" style="width: 4em;"> seconds.</p>
```

Give it 1em more....
Bildschirmfoto zu 2022-02-26 14-29-13

**Review by yubiuser — CHANGES_REQUESTED** [review]

File: settings.php (hunk 5 above)
Comment (DL6ER) [reply settings.php]: This is interesting, which browser (and possibly theme) is this? I tried with recent Firefox and Chrome and built-in themes on Linux and didn't see this.

**Review by yubiuser — APPROVED** [review]
