### PR TITLE
Prevent misleading warning being printed to the lighttpd error log when importing from teleporter backup

### LINKED ISSUE #2117: Warnings in lighttpd error log when using teleporter
Snip from https://github.com/pi-hole/docker-pi-hole/issues/686

---
In my own installation - _Docker Tag_ `2022.01.1` - I got a different error:
``` bash
$ docker exec -it pihole bash -c "tail -f /var/log/lighttpd/error.log"
2022-01-07 09:28:24: (server.c.1464) server started (lighttpd/1.4.53)
2022-02-12 10:33:20: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3::exec(): no such table: blacklist in /var/www/html/admin/scripts/pi-hole/php/teleporter.php on line 90
2022-02-12 10:33:20: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3::exec(): no such table: regex_blacklist in /var/www/html/admin/scripts/pi-hole/php/teleporter.php on line 90
2022-02-12 10:33:20: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3::exec(): no such table: whitelist in /var/www/html/admin/scripts/pi-hole/php/teleporter.php on line 90
2022-02-12 10:33:20: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3::exec(): no such table: regex_whitelist in /var/www/html/admin/scripts/pi-hole/php/teleporter.php on line 90
```
while reading on the browser:
```
Processed adlist (14 entries)
Processed adlist group assignments (14 entries)
Processed blacklist (exact) (0 entries)
Processed blacklist (regex) (0 entries)
Processed client (0 entries)
Processed client group assignments (0 entries)
Processed local DNS records (0 entries)
Processed domain_audit (1 entry)
Processed black-/whitelist group assignments (112 entries)
Processed group (2 entries)
Processed whitelist (exact) (110 entries)
Processed whitelist (regex) (2 entries)
OK
```

Edit @2022-02-12 10:40, and my sqlite DB looks like:
```
sqlite> .tables
adlist               domainlist_by_group  vw_gravity
adlist_by_group      gravity              vw_regex_blacklist
client               group                vw_regex_whitelist
client_by_group      info                 vw_whitelist
domain_audit         vw_adlist
domainlist           vw_blacklist
```
---
_Originally posted by @scara in https://github.com/pi-hole/docker-pi-hole/issues/686#issuecomment-1037089917_

### PR DESCRIPTION
**Pull request by PromoFaux**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Fixes #2117 by adding a check for table name before attempting to flush it

### CODE REVIEW

**Comment by yubiuser** [comment]
As I've been asked:
Rather then specify exactly which tables to ignore, skip the flush if the table does not exists. 
https://stackoverflow.com/questions/1601151/how-do-i-check-in-sqlite-whether-a-table-exists

**Comment by PromoFaux** [comment]
FP'd new code, tested by using adding some error logging into it as below:

```php
// Flush table if requested, only flush each table once
if($flush && !in_array($table, $flushed_tables))
{
	$tableExists = $db->querySingle("SELECT name FROM sqlite_master WHERE type='table' AND name='".$table."';");
	if ($tableExists)
	{
		error_log("doing ".$table);
		$db->exec("DELETE FROM \"".$table."\"");
		array_push($flushed_tables, $table);
	}
	else
	{
		error_log("not doing ".$table);
	}
}
```

Which outputs:

```
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:doing adlist
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:doing adlist_by_group
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:not doing blacklist
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:not doing regex_blacklist
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:doing client
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:doing client_by_group
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:doing domain_audit
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:doing domainlist_by_group
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:doing group
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:not doing whitelist
2022-02-12 13:31:15: mod_fastcgi.c.487) FastCGI-stderr:not doing regex_whitelist
```

File: scripts/pi-hole/php/teleporter.php [hunk 1]
```diff
@@ -84,11 +84,17 @@ function archive_restore_table($file, $table, $flush=false)
 	if(is_null($contents))
 		return 0;
 
+	$flush_ignore = array("blacklist", "regex_blacklist", "whitelist", "regex_whitelist");
```
Comment (yubiuser) [inline scripts/pi-hole/php/teleporter.php]:
```suggestion
```

File: scripts/pi-hole/php/teleporter.php [hunk 2]
```diff
@@ -84,11 +84,17 @@ function archive_restore_table($file, $table, $flush=false)
...
+
 	// Flush table if requested, only flush each table once
 	if($flush && !in_array($table, $flushed_tables))
 	{
-		$db->exec("DELETE FROM \"".$table."\"");
-		array_push($flushed_tables, $table);
+	 	$tableExists = $db->querySingle("SELECT name FROM sqlite_master WHERE type='table' AND name='".$table."';");
```
Comment (yubiuser) [inline scripts/pi-hole/php/teleporter.php]:
```suggestion
	 	// only flush if table exists
	 	$tableExists = $db->querySingle("SELECT name FROM sqlite_master WHERE type='table' AND name='".$table."';");
```

**Review by yubiuser — CHANGES_REQUESTED** [review]

File: scripts/pi-hole/php/teleporter.php (hunk 1 above)
Comment (PromoFaux) [reply scripts/pi-hole/php/teleporter.php]: Oh.. careless of me.

**Review by yubiuser — APPROVED** [review]
