### PR TITLE
Do not try to compare component version when remote version info is not available

### LINKED ISSUE #3728: No version is shown in footer if at least one remote version is missing/empty from versions file
### Versions

- Pi-hole:  v6.4
- Web:  v6.4.1
- FTL:  v6.5

### Platform

- OS and version:  Pi-hole Docker 2026.02.0
- Platform:  Synology

### Expected behavior

Locally used version should always be shown in the footer.

### Actual behavior / bug

In the [footer.js](https://github.com/pi-hole/web/blob/master/scripts/js/footer.js) the function to compare the versions doesn't handle `null` values. If the remote version (`v2`) is `null` it breaks, and leads to no versions being displayed in the footer at all.

A safety check to convert `null` values to string would resolve this, and at least the local version would always be displayed, i.e. with this at the beginning of the [`versionCompare`](https://github.com/pi-hole/web/blob/master/scripts/js/footer.js#L408) function:

```js
v1 = typeof v1 === "string" ? v1 : "";
v2 = typeof v2 === "string" ? v2 : "";
```

  Though this would not show to the user, that the update check was not successful, I would suggest to to implement a third state in the [JavaScript logic](https://github.com/pi-hole/web/blob/master/scripts/js/footer.js#L503-L570), to show that no remote version is known? Like the `N/A` in the `pihole -v` command.

### Steps to reproduce

1. Edit versions file (inside the Docker container at `/etc/pihole/versions`) to have at least one empty `GITHUB_*_VERSION=`-key, i.e. `GITHUB_WEB_VERSION=` (no value!).
2. Open web interface, versions are missing. Browser DevTools shows the error `Uncaught TypeError: can't access property 0, v2 is null`.

### Additional context

The empty/null value can happen if the curl calls fail for some reason in the [`updatecheck.sh`](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/updatecheck.sh) script, which leads to empty strings in the `/etc/pihole/versions` file, which in turn lead to `null` values returned from the `api/info/version` endpoint.

There also seems some mix in setting empty string (->`null`) and `"null"` in case of errors in the shell script.

In my specific case only the first curl call in the `updatecheck.sh` worked and all following failed for a reason I don't fully understand. Leading to the empty string/`null` values in the version file. I documented this behavior here: https://jonathanstroebele.de/notes/it-s-always-dns-pi-hole-curl-fritz-box

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

If (for any reason) we can't get the remote components version (and the API returns 'null' for that component), the [versionCompare](https://github.com/pi-hole/web/blob/master/scripts/js/footer.js#L408) function fails and the whole component information is not printed. 
This PR guards the `versionCompare` function by checking if the remote version != null. In this case, we skip the test and print a hint that the check failed.

Fixes https://github.com/pi-hole/web/issues/3728

In conjunction with https://github.com/pi-hole/pi-hole/pull/6550

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.2)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

File: scripts/js/footer.js [hunk 1]
```diff
@@ -516,7 +516,11 @@ function updateVersionInfo() {
               '" rel="noopener noreferrer" target="_blank">' +
               localVersion +
               "</a>";
-            if (versionCompare(v.local, v.remote) === -1) {
+            if (v.remote === null) {
+              // No remote version available, we cannot determine if an update is available
+              updateComponentAvailable = false;
```
Comment (rdwebdesign) [inline scripts/js/footer.js]: This variable was already set (line 506):

```suggestion
              // No remote version available, we cannot determine if an update is available
```

File: scripts/js/footer.js [hunk 2]
```diff
@@ -533,7 +537,12 @@ function updateVersionInfo() {
         }
 
         if (v.name === "Docker Tag") {
-          if (versionCompare(v.local, v.remote) === -1) {
+          if (v.remote === null) {
+            // No remote version available, we cannot determine if an update is available
+            updateComponentAvailable = false;
+            dockerUpdate = false;
```
Comment (rdwebdesign) [inline scripts/js/footer.js]: Same here:

- `updateComponentAvailable` is already `false` (line 506)
- `dockerUpdate` is already `false` (line 455)

```suggestion
            // No remote version available, we cannot determine if an update is available
```

**Review by rdwebdesign — CHANGES_REQUESTED** [review]
On the previous code, some variables were already set as `false` and they were only set as `true` when needed.

Some of these lines are redundant.

**Comment by rdwebdesign** [comment]
I'm not sure if we should add `Latest N/A` to each component, every time `versions` file is incomplete. 

Personally, I think this output will cause unnecessary worry for most users because they don't know what `N/A` means and don't know how to fix it.
Then we will see many issues saying the new release broke the version check.

I still don't know what is the best approach here.
What do you think about adding a text like this, in case of `version = null`?

image

**Comment by rdwebdesign** [comment]
@yubiuser 

To avoid messing with this PR, I created a new branch ([`fix/version2`](https://github.com/pi-hole/web/compare/fix/version...fix/version2)), based on your code, but I added another commit with my suggestions. If you didn't like it, feel free to say so.

**Comment by yubiuser** [comment]
I like it, esp. because it tells users how to fix the issue. Do you want to push the commit to this branch?

**Comment by rdwebdesign** [comment]
> Do you want to push the commit to this branch?

I'll do it.

**Review by rdwebdesign — APPROVED** [review]
Your code is approved _(I'm not sure if I should approve my own code, but it was just 1 commit)_.

**Comment by yubiuser** [comment]
I approve your code implicitly.
